sonar.host.url=https://sonarcloud.io
sonar.organization=alambritos-esen
sonar.projectKey=dream-parking_verificacion-online-onboarding
sonar.projectName=verificacion-online (onboarding)
sonar.sources=lib
sonar.tests=test
sonar.dart.lcov.reportPaths=coverage/lcov.info
